language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
env:
  global:
  - INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log
  - DISPLAY=:99.0
  - SCREENSHOT_ON_ERROR=1
  matrix:
  - DB=mysql TASK=travis:test
  - DB=derby TASK=travis:test
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=1"
  - DB=derby TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=1"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=2"
  - DB=derby TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=2"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=3"
  - DB=derby TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=3"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=4"
  - DB=derby TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=4"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=5"
  - DB=derby TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=5"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=6"
  - DB=derby TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=6"
  - DB=mysql TASK=travis:plugin:selenium
  - DB=derby TASK=travis:plugin:selenium
  - DB=mysql TASK=travis:plugin:test
  - DB=derby TASK=travis:plugin:test
  - TASK=dist
before_install:
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 2560x1700x24
- export DISPLAY=:99.0
before_script:
- sleep 3
- if [[ "$DB" == "mysql" ]]; then (mkdir lib; cd lib; curl -Oq http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar);
  fi
- if [[ "$DB" == "mysql" ]]; then export JAVA_OPTS="-Daspace.config.db_url=jdbc:mysql://localhost:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=root";
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database archivesspace default
  character set utf8;"; fi
- 'export JAVA_OPTS="-Xmx1G $JAVA_OPTS"'
- git clone --branch v1.5.0-RC3 https://github.com/archivesspace/archivesspace.git 
- ln -s $PWD archivesspace/plugins
- echo "AppConfig[:plugins] << 'remove_lang_warning' " > archivesspace/common/config/config.rb
- sed -i.bak "/Language - Property was missing/d" archivesspace/selenium/spec/resources_spec.rb
- sed -i.bak 's/ it "throws an error when no language is provided"/ xit "OVERRIDDDEN IN PLUGIN throws an error when no language is provided"/' archivesspace/backend/spec/model_resource_spec.rb
- cp build.xml archivesspace/build


branches:
  except:
  - gh-pages
script:
- archivesspace/build/run $TASK $TASK_OPTS
sudo: false
